// Fallback mock product data — used when the database is not yet connected.
// Mirrors prisma/seed.js so the UI is browseable out of the box.
import type { Product, Category } from '@/types';

export const mockCategories: Category[] = [
  { id: 'c1', name: 'Tools', slug: 'tools', icon: '🔧' },
  { id: 'c2', name: 'Building Materials', slug: 'building-materials', icon: '🧱' },
  { id: 'c3', name: 'Plumbing', slug: 'plumbing', icon: '🚿' },
  { id: 'c4', name: 'Electrical', slug: 'electrical', icon: '⚡' },
  { id: 'c5', name: 'Paint', slug: 'paint', icon: '🎨' },
  { id: 'c6', name: 'Garden', slug: 'garden', icon: '🌱' },
  { id: 'c7', name: 'Hardware', slug: 'hardware', icon: '🔩' },
  { id: 'c8', name: 'Lighting', slug: 'lighting', icon: '💡' },
  { id: 'c9', name: 'Roof Sealing', slug: 'roof-sealing', icon: '🏠' },
  { id: 'c10', name: 'Stone & Aggregates', slug: 'building-stone', icon: '🪨', parentSlug: 'building-materials' },
  { id: 'c11', name: 'Grouts', slug: 'building-grouts', icon: '🫙', parentSlug: 'building-materials' },
  { id: 'c12', name: 'Adhesives & Thinsets', slug: 'building-adhesives', icon: '🔗', parentSlug: 'building-materials' },
  { id: 'c13', name: 'Waterproofing', slug: 'building-waterproofing', icon: '💧', parentSlug: 'building-materials' },
  { id: 'c14', name: 'Mortars & Cement', slug: 'building-mortars', icon: '🏗️', parentSlug: 'building-materials' },
  { id: 'c15', name: 'Primers & Bonding', slug: 'building-primers', icon: '🫧', parentSlug: 'building-materials' },
  { id: 'c16', name: 'Concrete Treatment', slug: 'building-concrete-treatment', icon: '🔩', parentSlug: 'building-materials' },
  { id: 'c17', name: 'Tile Tools', slug: 'building-tile-tools', icon: '🪛', parentSlug: 'building-materials' },
  { id: 'c18', name: 'Construction Paints', slug: 'building-paints', icon: '🖌️', parentSlug: 'building-materials' },
  { id: 'c20', name: 'Hand Tools', slug: 'tools-hand-tools', icon: '🔨', parentSlug: 'tools' },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'DEWALT 20V MAX Cordless Drill Kit',
    slug: 'dewalt-20v-cordless-drill',
    description: 'Compact, lightweight design fits into tight areas. High performance motor delivers 300 unit watts out (UWO) of power. Includes 2 batteries, charger, and case.',
    price: 199.99,
    comparePrice: 249.99,
    stock: 45,
    barcode: '885911599832',
    sku: 'DW-DCD771C2',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600',
    brand: 'DEWALT',
    rating: 4.8,
    reviewCount: 1247,
    featured: true,
    categoryId: 'c1',
  },
  {
    id: 'p2',
    name: 'Quikrete 60 lb. Concrete Mix',
    slug: 'quikrete-concrete-mix',
    description: 'Original 4000 PSI average compressive strength concrete mix. Use for any general concrete application. Just add water.',
    price: 6.48,
    stock: 320,
    barcode: '039645011010',
    sku: 'QK-1101-60',
    imageUrl: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=600',
    brand: 'Quikrete',
    rating: 4.6,
    reviewCount: 892,
    featured: true,
    categoryId: 'c14',
  },
  {
    id: 'p3',
    name: 'Moen Single-Handle Kitchen Faucet',
    slug: 'moen-kitchen-faucet',
    description: 'Chrome finish with pull-down sprayer. Lifetime limited warranty. Easy installation with included hardware.',
    price: 159.00,
    comparePrice: 199.00,
    stock: 28,
    barcode: '026508295731',
    sku: 'MN-87039',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600',
    brand: 'Moen',
    rating: 4.7,
    reviewCount: 543,
    featured: true,
    categoryId: 'c3',
  },
  {
    id: 'p4',
    name: 'Romex 12/2 Indoor Electrical Wire 250ft',
    slug: 'romex-12-2-wire',
    description: 'NM-B 12/2 with ground. UL listed. For indoor residential use in dry locations.',
    price: 189.00,
    stock: 67,
    barcode: '038902031495',
    sku: 'RX-12-2-250',
    imageUrl: 'https://images.unsplash.com/photo-1565608087341-404b25492fee?w=600',
    brand: 'Southwire',
    rating: 4.9,
    reviewCount: 234,
    featured: false,
    categoryId: 'c4',
  },
  {
    id: 'p5',
    name: 'BEHR Premium Plus Interior Paint 1 Gal',
    slug: 'behr-interior-paint',
    description: 'Low VOC, eggshell finish. Excellent coverage and durability. Available in thousands of colors.',
    price: 32.98,
    stock: 156,
    barcode: '082474200056',
    sku: 'BH-PP-INT-1G',
    imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600',
    brand: 'BEHR',
    rating: 4.7,
    reviewCount: 2103,
    featured: true,
    categoryId: 'c5',
  },
  {
    id: 'p6',
    name: 'Miracle-Gro Garden Soil 1 cu ft',
    slug: 'miracle-gro-soil',
    description: 'Enriched with continuous release plant food. Feeds for up to 3 months. For in-ground use.',
    price: 8.97,
    stock: 412,
    barcode: '073561720205',
    sku: 'MG-GS-1CF',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600',
    brand: 'Miracle-Gro',
    rating: 4.5,
    reviewCount: 1567,
    featured: false,
    categoryId: 'c6',
  },
  {
    id: 'p7',
    name: 'Stanley 25ft Tape Measure',
    slug: 'stanley-tape-measure',
    description: 'Heavy-duty tape with Mylar coating for extended blade life. Lifetime warranty.',
    price: 14.97,
    stock: 89,
    barcode: '076174330259',
    sku: 'ST-33-425',
    imageUrl: 'https://images.unsplash.com/photo-1426927308491-6380b6a9936f?w=600',
    brand: 'Stanley',
    rating: 4.8,
    reviewCount: 3421,
    featured: false,
    categoryId: 'c1',
  },
  {
    id: 'p8',
    name: 'LED 60W Equivalent Daylight Bulb 4-Pack',
    slug: 'led-60w-bulb-4pack',
    description: 'Energy-saving LED bulb. 800 lumens. 5000K daylight. Lasts up to 15,000 hours.',
    price: 9.97,
    stock: 234,
    barcode: '046135710179',
    sku: 'LED-60W-4PK',
    imageUrl: 'https://images.unsplash.com/photo-1550985543-49bee3167284?w=600',
    brand: 'EcoSmart',
    rating: 4.6,
    reviewCount: 4521,
    featured: true,
    categoryId: 'c8',
  },
  {
    id: 'p9',
    name: 'Everbilt 5lb Box of Drywall Screws',
    slug: 'everbilt-drywall-screws',
    description: 'Coarse thread, bugle head. Phosphate coated. For wood studs.',
    price: 18.47,
    stock: 145,
    barcode: '030699137497',
    sku: 'EB-DS-5LB',
    imageUrl: 'https://images.unsplash.com/photo-1609205807490-89c0d6c8c5ea?w=600',
    brand: 'Everbilt',
    rating: 4.7,
    reviewCount: 678,
    featured: false,
    categoryId: 'c7',
  },
  {
    id: 'p10',
    name: 'RYOBI 18V Circular Saw',
    slug: 'ryobi-circular-saw',
    description: '5-1/2 in. blade. Lightweight design. Tool only - battery sold separately.',
    price: 79.00,
    stock: 32,
    barcode: '033287204472',
    sku: 'RY-P505',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'RYOBI',
    rating: 4.6,
    reviewCount: 891,
    featured: false,
    categoryId: 'c1',
  },
  {
    id: 'p11',
    name: 'PEX Tubing 1/2 in. x 100 ft',
    slug: 'pex-tubing-half-inch',
    description: 'Red PEX-B for hot water lines. NSF certified. Flexible and durable.',
    price: 38.50,
    stock: 78,
    barcode: '079916020013',
    sku: 'PEX-12-100R',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=600',
    brand: 'SharkBite',
    rating: 4.8,
    reviewCount: 312,
    featured: false,
    categoryId: 'c3',
  },
  {
    id: 'p12',
    name: 'Heavy Duty Wheelbarrow 6 cu ft',
    slug: 'wheelbarrow-6cuft',
    description: 'Steel tray, hardwood handles. Pneumatic tire. Great for gardening and construction.',
    price: 89.00,
    comparePrice: 119.00,
    stock: 24,
    barcode: '745035811563',
    sku: 'WB-6CF-HD',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600',
    brand: 'True Temper',
    rating: 4.5,
    reviewCount: 234,
    featured: false,
    categoryId: 'c6',
  },
  {
    id: 'p16',
    name: 'Piedra 3/4"',
    slug: 'piedra-3-4',
    description: 'Piedra triturada gris de 3/4 de pulgada. Ideal para mezclas de concreto, relleno de cimientos, drenaje y proyectos de construcción en general. Alta resistencia y durabilidad. Vendida por saco de 50 lbs.',
    price: 9.99,
    stock: 500,
    barcode: '787756200016',
    sku: 'NC-PIEDRA-34',
    imageUrl: 'https://scontent.fhsv1-1.fna.fbcdn.net/v/t39.30808-6/565815375_122136809828932196_7834805027321434769_n.jpg?stp=cp6_dst-jpg_tt6&_nc_cat=110&ccb=1-7&_nc_sid=7b2446&_nc_ohc=DK-V7kGQsKsQ7kNvwEC1FPz&_nc_oc=Ado3NKDdLAnIxqTLN2_5M88ynWMlZmk2zTiPM-cBKFSKXEHWKy4fiSQnIDmugMv0vCs&_nc_zt=23&_nc_ht=scontent.fhsv1-1.fna&_nc_gid=OM8FWrwj1c_J0kHDne4fmw&_nc_ss=7b2a8&oh=00_Af4fUr93oxTiAiAJO8LnnV4oC6jOZBaLZojgu05wIslgOA&oe=6A083453',
    brand: 'Naguabo Commercial',
    rating: 4.8,
    reviewCount: 62,
    featured: false,
    categoryId: 'c10',
  },
  {
    id: 'p17',
    name: 'Piedra Blanca 3/4"',
    slug: 'piedra-blanca-3-4',
    description: 'Piedra caliza blanca triturada de 3/4 de pulgada. Perfecta para paisajismo, caminos decorativos, drenaje y construcción. Su tono claro aporta un acabado limpio y elegante. Vendida por saco de 50 lbs.',
    price: 14.99,
    stock: 320,
    barcode: '787756200023',
    sku: 'NC-PIEDRA-BL-34',
    imageUrl: 'https://scontent.fhsv1-1.fna.fbcdn.net/v/t39.30808-6/560579298_122136809822932196_5845496087678000448_n.jpg?stp=cp6_dst-jpg_tt6&_nc_cat=104&ccb=1-7&_nc_sid=7b2446&_nc_ohc=xof0Kpo7ikAQ7kNvwHnnH9w&_nc_oc=AdpSjm0T6yJNkOxpN59nLmlhkoKC5bYHYHV-8z-V5Oxy1v3OFea6zClsCV5PvFfJQtc&_nc_zt=23&_nc_ht=scontent.fhsv1-1.fna&_nc_gid=CzUWhuOGeUu0QMtl9_3L1A&_nc_ss=7b2a8&oh=00_Af6Xtwblgi1J0uaX83kQ0a7JVX7OndxSAF-H9jCxNpZnyA&oe=6A082D32',
    brand: 'Naguabo Commercial',
    rating: 4.7,
    reviewCount: 45,
    featured: false,
    categoryId: 'c10',
  },
  {
    id: 'p18',
    name: 'Piedra Dalmata',
    slug: 'piedra-dalmata',
    description: 'Piedra decorativa dálmata con patrón gris y blanco moteado. Ideal para jardines, caminos, paisajismo y proyectos decorativos exteriores. Resistente a la intemperie, bajo mantenimiento y de gran atractivo visual. Vendida por saco de 50 lbs.',
    price: 18.99,
    stock: 210,
    barcode: '787756200030',
    sku: 'NC-PIEDRA-DAL',
    imageUrl: 'https://scontent.fhsv1-1.fna.fbcdn.net/v/t39.30808-6/561149727_122136809756932196_1929447874476423109_n.jpg?stp=cp6_dst-jpg_tt6&_nc_sid=7b2446&_nc_ohc=gnnUEjEsvucQ7kNvwEsg6PR&_nc_oc=AdpCifsM3EdJyQVtWHqJGvNxVX0AbOgVQxQxrElt1uuf7IfTW38C1mqwfdetCqHVmvY&_nc_zt=23&_nc_ht=scontent.fhsv1-1.fna&_nc_gid=2668lkzGq3BYvqVOnzG4uw&_nc_ss=7b2a8&oh=00_Af4sPe0bX7T-WaN_wdcZ7TaPhEBya4L4QwrMh-ziiBF1fw&oe=6A085F3F',
    brand: 'Naguabo Commercial',
    rating: 4.9,
    reviewCount: 38,
    featured: false,
    categoryId: 'c10',
  },
  {
    id: 'p13',
    name: 'Crossco® Water Guard™ 5 Gal',
    slug: 'crossco-water-guard',
    description: 'High-performance 3-in-1 sealant, primer, and paint with strong resistance to alkalinity. Hydrophobic Bio-Pruf Technology waterproofs roofs and walls against water, moisture, and leaks. Stain resistant, energy-saving, and easy to clean. Available in matte or satin finish.',
    price: 59.99,
    comparePrice: 74.99,
    stock: 40,
    barcode: '787756100221',
    sku: 'CC-WG-5G',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/WG_satin.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 198,
    featured: true,
    categoryId: 'c9',
  },
  {
    id: 'p14',
    name: 'Crossco® Tropical Flat™ 1 Gal',
    slug: 'crossco-tropical-flat',
    description: 'Matte latex paint formulated with acrylic resin for a smooth and uniform finish. Ideal for interior or exterior use on cement, wood, brick, and metal surfaces. Resistant to fungal growth, quick drying (touch-dry in 1 hour, recoat in 5 hours), and long-lasting durability.',
    price: 28.99,
    stock: 85,
    barcode: '787756100238',
    sku: 'CC-TF-1G',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2015/11/tropical_flat1.png',
    brand: 'CROSSCO',
    rating: 4.5,
    reviewCount: 134,
    featured: false,
    categoryId: 'c5',
  },
  {
    id: 'p15',
    name: 'Crossco® Tropical Gloss™ 1 Gal',
    slug: 'crossco-tropical-gloss',
    description: 'Semi-gloss latex paint suitable for interior or exterior surfaces. Designed for industrial, commercial, and residential use on cement, wood, brick, and metal. Fungus resistant, does not yellow over time, easy to clean, and touch-dry in 1 hour.',
    price: 32.99,
    stock: 72,
    barcode: '787756100245',
    sku: 'CC-TG-1G',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2015/11/tropical_gloss-2.png',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 109,
    featured: false,
    categoryId: 'c5',
  },
  {
    id: 'p19',
    name: 'Crossco® Cross-Quick™',
    slug: 'crossco-cross-quick',
    description: 'A polymer-modified cement-based underlayment that creates a free flowing liquid mortar seeking its own level and producing a smooth, hard, flat surface. Self-leveling — requires only water addition for application.',
    price: 24.99,
    stock: 60,
    barcode: '787756300010',
    sku: 'CQ001',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/crossquick1.jpg',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 54,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p20',
    name: 'Black Jack® Emulsion Roof Coating',
    slug: 'black-jack-emulsion-roof-coating',
    description: 'A liquid-applied, asphalt-based coating that penetrates and seals worn roof surfaces, foundation block walls, above or below grade masonry surfaces. Weatherproofs surfaces and can be applied to underground wood footings and metal surfaces, drying to a black finish.',
    price: 34.99,
    stock: 48,
    barcode: '787756300027',
    sku: 'BJ-EMULSION',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/black-jack-emulsion.png',
    brand: 'CROSSCO',
    rating: 4.5,
    reviewCount: 87,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p21',
    name: 'Crossco® Super White™',
    slug: 'crossco-super-white',
    description: 'A water-based acrylic modified PVDF roof coating offering the ultimate in reflectivity, color stability, and weather-resistant performance. Maintains flexibility while providing durable protection against environmental elements. Designed as a protective finishing coat for roofing applications.',
    price: 49.99,
    stock: 55,
    barcode: '787756300034',
    sku: 'RS077',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/SuperWhite1.jpg',
    brand: 'CROSSCO',
    rating: 4.8,
    reviewCount: 143,
    featured: true,
    categoryId: 'c9',
  },
  {
    id: 'p22',
    name: 'Crossco® 4500™',
    slug: 'crossco-4500',
    description: 'A water-based, single-component acrylic elastomeric sealer with fiber reinforcement that turns ultra white and reduces interior temperature. Functions as both primer and sealer, providing waterproof protection without requiring a separate primer application.',
    price: 39.99,
    stock: 70,
    barcode: '787756300041',
    sku: 'RS085',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/45002.jpg',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 112,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p23',
    name: 'Crossco® 5500™',
    slug: 'crossco-5500',
    description: 'A water-based 100% acrylic elastomeric single-component coating providing a waterproof seal on roofs and walls. Silicone-modified formula reflects sunlight to reduce internal temperature and help lower energy expenses.',
    price: 44.99,
    stock: 65,
    barcode: '787756300058',
    sku: 'RS088',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/55002.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 98,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p24',
    name: 'Crossco® 8500™',
    slug: 'crossco-8500',
    description: 'A water-based, 100% acrylic elastomeric sealer with super fast dry film formation, water repellency, and low water absorption paired with strong mechanical properties. Single-component design for quick-drying application.',
    price: 49.99,
    stock: 50,
    barcode: '787756300065',
    sku: 'RS100',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/85002.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 76,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p25',
    name: 'Crossco® ES 2000 Plus™',
    slug: 'crossco-es-2000-plus',
    description: 'An advanced roof sealer featuring 100% acrylic with a high quality brilliant white finish that provides a strong reflecting coat to protect the roof surface. Will not crack or peel despite severe weather or joint movement.',
    price: 42.99,
    stock: 80,
    barcode: '787756300072',
    sku: 'RS050',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/es2000_plus1.jpg',
    brand: 'CROSSCO',
    rating: 4.8,
    reviewCount: 201,
    featured: true,
    categoryId: 'c9',
  },
  {
    id: 'p26',
    name: 'Crossco® ES 2000 Primer™',
    slug: 'crossco-es-2000-primer',
    description: 'A styrene acrylic UV-stable resin membrane designed to penetrate material porosity and provide substrate adhesion and waterproofing. Seals and cures concrete while remaining tacky for best adhesion, drying clear.',
    price: 29.99,
    stock: 90,
    barcode: '787756300089',
    sku: 'RS060',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2015/02/es2000primer1.jpg',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 88,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p27',
    name: 'Crossco® ES 2000 Sealer™',
    slug: 'crossco-es-2000-sealer',
    description: 'A styrene acrylic silicone-modified mastic designed to protect various roof surfaces. This elastomeric sealant expands and contracts with the surface, maintaining its mechanical properties after sun and rain exposure.',
    price: 39.99,
    stock: 75,
    barcode: '787756300096',
    sku: 'RS001',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/12/es2000Sealer.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 119,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p28',
    name: 'Crossco® EZ Seal System Sealer™',
    slug: 'crossco-ez-seal-system-sealer',
    description: 'A fast-drying white elastomeric coating with Thermal Crystal Technology that functions as both primer and sealer. Bonds easily to many surfaces, forms an elastic membrane that resists cracking and peeling — two coats can be applied the same day.',
    price: 44.99,
    stock: 60,
    barcode: '787756300102',
    sku: 'RS032',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/sf95001.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 93,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p29',
    name: 'Crossco® EZ Seal System Max White™',
    slug: 'crossco-ez-seal-system-max-white',
    description: 'A high-performance roof coating featuring Kynar Aquatec® PVDF fluoropolymer resin technology — the ultimate in thermal reflectivity, color stability, and weather resistance. Tough, durable finish that resists years of environmental exposure.',
    price: 54.99,
    stock: 45,
    barcode: '787756300119',
    sku: 'RS031',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/maxWHite1.jpg',
    brand: 'CROSSCO',
    rating: 4.9,
    reviewCount: 67,
    featured: true,
    categoryId: 'c9',
  },
  {
    id: 'p30',
    name: 'Crossco® Perma Seal Acrylic™',
    slug: 'crossco-perma-seal-acrylic',
    description: 'A roof and walls sealer featuring a white finish reinforced with silicone and acrylic technology. The reflective white coating deflects UV rays and reduces internal temperatures; water-based formula ensures easy cleanup with minimal odor.',
    price: 38.99,
    stock: 68,
    barcode: '787756300126',
    sku: 'RS026',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2015/03/PS-Acrilico1.jpg',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 105,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p31',
    name: 'Crossco® Max-Flex 5500™',
    slug: 'crossco-max-flex-5500',
    description: 'A water-based, single-component elastomeric sealer engineered with fibers for volume and hardness. Applies blue and dries to a white finish, providing excellent waterproofing capabilities while maintaining full elasticity.',
    price: 47.99,
    stock: 52,
    barcode: '787756300133',
    sku: 'RS106',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/maxFlex1.jpg',
    brand: 'CROSSCO',
    rating: 4.8,
    reviewCount: 81,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p32',
    name: 'Crossco® ES-2000 Plus Ultra White USA™',
    slug: 'crossco-es-2000-plus-ultra-white-usa',
    description: 'A single-component, 100% acrylic sealer and roof coating providing an Ultra White Finish that lowers interior temperature in homes, industrial, and commercial buildings. Resists cracking and peeling despite severe weather conditions.',
    price: 54.99,
    stock: 40,
    barcode: '787756300140',
    sku: 'RS050-USA',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/es2000PlusUSA1.jpg',
    brand: 'CROSSCO',
    rating: 4.8,
    reviewCount: 59,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p33',
    name: 'Crossco® EZ Seal System Primer™',
    slug: 'crossco-ez-seal-system-primer',
    description: 'A rubberized undercoat containing styrene butadiene synthetic rubber designed to improve adhesion and create a waterproof base. High-solids formula seals porous materials and cracks, providing the ideal base for any EZ Seal System top coat.',
    price: 27.99,
    stock: 85,
    barcode: '787756300157',
    sku: 'RS010',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/ez_primer1.jpg',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 72,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p34',
    name: 'Crossco® Ultra Seal Plus™',
    slug: 'crossco-ultra-seal-plus',
    description: 'A water-based, single-component acrylic elastomeric sealer featuring a hybrid film system for fast-dry waterproof finish with excellent elasticity and UV/mildew resistance. Fast-drying technology enables two coats to be applied the same day.',
    price: 46.99,
    stock: 58,
    barcode: '787756300164',
    sku: 'RS098',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/UltraSealPlus1.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 94,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p35',
    name: 'Crossco® Ultra Seal™',
    slug: 'crossco-ultra-seal',
    description: 'An elastomeric roof coating formulated with 100% acrylic polymer that provides outstanding adhesion, superior reflectivity, and resists cracking and peeling. Applies blue and dries white for easy coverage verification.',
    price: 44.99,
    stock: 62,
    barcode: '787756300171',
    sku: 'RS089',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/UltraSeal1.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 108,
    featured: false,
    categoryId: 'c9',
  },
  {
    id: 'p36',
    name: 'Crossco® 6500™',
    slug: 'crossco-6500',
    description: 'A water-based acrylic elastomeric sealer formulated as a single-component, high-solids coating designed to waterproof roofs and walls. Fast-drying formula creates a durable protective barrier that resists cracking, crumbling, or peeling even under severe weather conditions.',
    price: 42.99,
    stock: 55,
    barcode: '787756300188',
    sku: 'RS092',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/65002.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 88,
    featured: false,
    categoryId: 'c9',
  },
  {
    /* ── WECO Solutions — Building Materials ── */
    id: 'p38',
    name: 'Weco W701 Sanded Grout',
    slug: 'weco-w701-sanded-grout',
    description: 'Sanded cement grout for residential and commercial tile joints. Available in 20 colors. 10 LB and 25 LB sizes.',
    price: 12.99,
    stock: 120,
    barcode: '787787701010',
    sku: 'W701',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w701-sanded-grout-8566934.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 98,
    featured: false,
    categoryId: 'c11',
  },
  {
    id: 'p39',
    name: 'Weco W704 PolyGrout HD',
    slug: 'weco-w704-polygrout-hd',
    description: 'Polymer-modified cement grout for enhanced performance. Superior stain resistance and flexibility. Available in 20 colors in 10 LB and 25 LB sizes.',
    price: 14.99,
    stock: 95,
    barcode: '787787704010',
    sku: 'W704',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w704-polygrout-hd-7444160.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 74,
    featured: false,
    categoryId: 'c11',
  },
  {
    id: 'p40',
    name: 'Weco W573 Unsanded Grout',
    slug: 'weco-w573-unsanded-grout',
    description: 'Unsanded cement grout for narrow tile joints (1/8" or less). Ideal for wall tiles, glass, and polished stone. Available in 20 colors.',
    price: 12.99,
    stock: 110,
    barcode: '787787573010',
    sku: 'W573',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w573-unsanded-grout-7090221.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 62,
    featured: false,
    categoryId: 'c11',
  },
  {
    id: 'p41',
    name: 'Weco W705 Epoxy Color 2K',
    slug: 'weco-w705-epoxy-color-2k',
    description: 'Two-component epoxy grout system offering superior chemical resistance, stain resistance, and durability. Available in Pearl White, Cement Gray, and Graphite.',
    price: 76.99,
    stock: 40,
    barcode: '787787705010',
    sku: 'W705',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w705-epoxy-color-2k-3199134.jpg',
    brand: 'WECO',
    rating: 4.8,
    reviewCount: 43,
    featured: false,
    categoryId: 'c11',
  },
  {
    id: 'p42',
    name: 'Weco W707 Epoxy Kleen G',
    slug: 'weco-w707-epoxy-kleen-g',
    description: 'Epoxy grout and film remover cleaning solution. Safely dissolves epoxy residue from tile surfaces without damaging grout joints.',
    price: 35.99,
    stock: 55,
    barcode: '787787707010',
    sku: 'W707',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w707-epoxy-kleen-g-8966489.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 38,
    featured: false,
    categoryId: 'c11',
  },
  {
    id: 'p43',
    name: 'Weco W3000 ZERO Thin Set Mortar',
    slug: 'weco-w3000-zero-thinset',
    description: 'Thin set mortar formulated for low-absorption tiles and water-immersion installations. Works with marble, glass, mosaic, porcelain, ceramic, and natural stone. ANSI A118.4 & A118.11 compliant. 50 LB bag.',
    price: 42.99,
    stock: 80,
    barcode: '787787300010',
    sku: 'W3000-ZERO',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w3000-zero-1988533.jpg',
    brand: 'WECO',
    rating: 4.8,
    reviewCount: 87,
    featured: true,
    categoryId: 'c12',
  },
  {
    id: 'p44',
    name: 'Weco W3000 XLF Large Format Thinset',
    slug: 'weco-w3000-xlf-thinset',
    description: 'High-performance adhesive for large format tiles, natural stone, and difficult substrates. Designed for slabs and tiles over 15"x15". 50 LB bag.',
    price: 39.99,
    stock: 70,
    barcode: '787787300020',
    sku: 'W3000-XLF',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w3000-xlf-4935237.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 56,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p45',
    name: 'Weco W3000 FAST Thinset',
    slug: 'weco-w3000-fast-thinset',
    description: 'Fast-setting polymer-modified tile adhesive. Achieves walkable strength in 2–3 hours. Ideal for accelerated tile installation projects. 50 LB bag.',
    price: 42.99,
    stock: 65,
    barcode: '787787300030',
    sku: 'W3000-FAST',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w3000-fast-7571231.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 49,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p46',
    name: 'Weco W900 PRO Polymer Mortar',
    slug: 'weco-w900-pro-polymer-mortar',
    description: 'Advanced polymer mortar technology for superior bonding and flexibility on floors and walls. Available in Gray and White. High performance for demanding installations.',
    price: 9.99,
    stock: 150,
    barcode: '787787900010',
    sku: 'W900-PRO',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w900-pro-2023670.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 112,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p47',
    name: 'Weco W759 Floor Thinset Gray 50 LB',
    slug: 'weco-w759-floor-thinset-gray',
    description: 'Reliable floor thinset mortar in gray. Suitable for residential and light commercial floor tile installations. 50 LB bag.',
    price: 10.99,
    stock: 200,
    barcode: '787787759010',
    sku: 'W759',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w759-4419037.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 134,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p48',
    name: 'Weco W761 Wall/Floor Thinset White 50 LB',
    slug: 'weco-w761-wall-floor-thinset-white',
    description: 'Versatile white thinset mortar for wall and floor tile applications. Ideal for light-colored and translucent tiles where gray mortar may show through. 50 LB bag.',
    price: 12.99,
    stock: 175,
    barcode: '787787761010',
    sku: 'W761',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w761-5236435.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 108,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p49',
    name: 'Weco W220 Tile Grip Mastic',
    slug: 'weco-w220-tile-grip-mastic',
    description: 'Pre-mixed mastic adhesive ideal for fast tile installation on walls and floors. No mixing required. Available in 1 GAL, 3.5 GAL, and 40 LB.',
    price: 27.99,
    stock: 85,
    barcode: '787787220010',
    sku: 'W220',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w220-tile-grip-3253043.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 76,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p50',
    name: 'Weco W1000 Polymer-Modified Mortar',
    slug: 'weco-w1000-polymer-mortar',
    description: 'Premium polymer-modified mortar with advanced bonding properties for ceramic, porcelain, and natural stone on walls and floors. Available in Gray and White.',
    price: 17.99,
    stock: 130,
    barcode: '787787100010',
    sku: 'W1000',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w1000-9185869.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 91,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p51',
    name: 'Weco W120 Solid Bond Blue Bonding Agent',
    slug: 'weco-w120-solid-bond-blue',
    description: 'Bonding agent that creates a strong mechanical key between old and new concrete or plaster surfaces. Available in 1 GAL and 5 GAL.',
    price: 18.99,
    stock: 90,
    barcode: '787787120010',
    sku: 'W120',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w120-solid-bond-blue-4813366.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 67,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p52',
    name: 'Weco W130 Rough Bond Yellow Bonding Agent',
    slug: 'weco-w130-rough-bond-yellow',
    description: 'High-performance yellow bonding agent for rough or porous substrates. Improves adhesion between layers in plaster, stucco, and tile applications. 1 GAL and 5 GAL.',
    price: 21.99,
    stock: 75,
    barcode: '787787130010',
    sku: 'W130',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w130-rough-bond-yellow-7858249.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 53,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p53',
    name: 'Weco W800+ Durokryl Latex & Bonding Agent',
    slug: 'weco-w800-plus-durokryl',
    description: 'Acrylic latex and bonding agent that enhances mortar strength, bonding, and flexibility. Can be used as a bonding agent or mixed with cement. Available in 1 GAL and 5 GAL.',
    price: 38.99,
    stock: 60,
    barcode: '787787800020',
    sku: 'W800PLUS',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w800-durokryl-latex-bonding-agent-7893628.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 44,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p54',
    name: 'Enco Red Contact Cement',
    slug: 'enco-red-contact-cement',
    description: 'Professional-grade contact cement for bonding laminates, rubber, leather, and other materials. Fast-drying and waterproof. Available in 1 GAL and 5 GAL.',
    price: 39.99,
    stock: 48,
    barcode: '787787000540',
    sku: 'ENCO-CC-RED',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/contact-cement-4201245.jpg',
    brand: 'Enco',
    rating: 4.6,
    reviewCount: 58,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p55',
    name: 'Weco W360 Mortar Fast Rapid-Set',
    slug: 'weco-w360-mortar-fast',
    description: 'Rapid-setting mortar for structural construction and concrete repair. Sets in 15 minutes, achieves >2500 PSI structural strength in 1 hour. For vertical, overhead, pavement, and concrete surfaces. ASTM C928 R3 & C387. 50 LB bag.',
    price: 24.99,
    stock: 70,
    barcode: '787787360010',
    sku: 'W360',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w360-mortar-fast-6224837.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 61,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p56',
    name: 'Weco W440 Structural Mortar',
    slug: 'weco-w440-structural-mortar',
    description: 'High-strength structural repair mortar for concrete restoration and patching. Excellent bonding to existing concrete surfaces.',
    price: 13.99,
    stock: 85,
    barcode: '787787440010',
    sku: 'W440',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w440-structural-mortar-3740919.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 47,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p57',
    name: 'Weco W511 Aqua Plug Hydraulic Cement',
    slug: 'weco-w511-aqua-plug-hydraulic-cement',
    description: 'Hydraulic cement that stops active water leaks in concrete, masonry, and stone. Sets in 3–5 minutes. Ideal for basements, pools, and retaining walls.',
    price: 19.99,
    stock: 95,
    barcode: '787787511010',
    sku: 'W511',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w511-aqua-plug-hydraulic-cement-2820239.jpg',
    brand: 'WECO',
    rating: 4.8,
    reviewCount: 83,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p58',
    name: 'Weco W710 Concrete Renew Kit',
    slug: 'weco-w710-concrete-renew-kit',
    description: 'Complete concrete renewal system for restoring worn or damaged concrete floors. Includes everything needed for a professional finish.',
    price: 25.99,
    stock: 45,
    barcode: '787787710010',
    sku: 'W710',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w710-concrete-renew-kit-5004737.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 34,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p59',
    name: 'Weco W501 LevelTech Floor Leveling Kit',
    slug: 'weco-w501-leveltech-kit',
    description: 'Complete leveling system kit for achieving perfectly flat floors before tile installation. Covers uneven substrates and minor imperfections.',
    price: 45.99,
    stock: 38,
    barcode: '787787501020',
    sku: 'W501-LT',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w501-leveltech-kit-4886638.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 29,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p60',
    name: 'Weco W350 Plaster Mix',
    slug: 'weco-w350-plaster-mix',
    description: 'Ready-to-mix plaster formulation for interior and exterior walls and ceilings. Smooth finish, excellent workability, and strong adhesion.',
    price: 5.89,
    stock: 250,
    barcode: '787787350010',
    sku: 'W350',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w350-plaster-mix-6500859.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 142,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p61',
    name: 'Weco W450 Concrete Mix',
    slug: 'weco-w450-concrete-mix',
    description: 'Pre-mixed concrete formulation for general construction, footings, slabs, and repairs. High compressive strength and durability.',
    price: 8.99,
    stock: 300,
    barcode: '787787450010',
    sku: 'W450',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w450-concrete-mix-5841482.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 189,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p62',
    name: 'Weco W250 Marble Sand',
    slug: 'weco-w250-marble-sand',
    description: 'Fine marble sand for decorative plaster, stucco finishes, and terrazzo applications. Provides a smooth, attractive surface texture.',
    price: 6.99,
    stock: 180,
    barcode: '787787250010',
    sku: 'W250',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w250-marble-sand-2658914.jpg',
    brand: 'WECO',
    rating: 4.4,
    reviewCount: 67,
    featured: false,
    categoryId: 'c10',
  },
  {
    id: 'p63',
    name: 'Weco W180 Plaster Finish',
    slug: 'weco-w180-plaster-finish',
    description: 'Fine finishing plaster for achieving smooth interior surfaces. Applies over base coats to deliver a professional-grade wall finish.',
    price: 14.99,
    stock: 130,
    barcode: '787787180010',
    sku: 'W180',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w180-plaster-finish-1294.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 78,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p64',
    name: 'Weco W400 White Cement Ultra',
    slug: 'weco-w400-white-cement-ultra',
    description: 'Premium white cement for decorative concrete, architectural finishes, grout, and tile adhesive. High brightness and consistent color. Available in multiple sizes.',
    price: 7.49,
    stock: 220,
    barcode: '787787400010',
    sku: 'W400',
    imageUrl: 'https://wecosolutions.com/cdn/shop/products/w-400-white-cement-ultra-4406923.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 154,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p65',
    name: 'Weco W151 Barrier Ultra Primer',
    slug: 'weco-w151-barrier-ultra-primer',
    description: 'Construction primer designed to enhance bonding strength and surface compatibility. Creates an effective moisture barrier. Available in 1 GAL and 3.5 GAL.',
    price: 51.99,
    stock: 45,
    barcode: '787787151010',
    sku: 'W151',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w151-barrier-ultra-9228525.jpg',
    brand: 'WECO',
    rating: 4.7,
    reviewCount: 41,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p66',
    name: 'Weco W160 Prime-2 Bond Primer',
    slug: 'weco-w160-prime-2-bond-primer',
    description: 'High-performance construction primer that enhances bonding strength between substrate and adhesive layers. Reduces porosity and improves tile adhesion. 1 GAL and 3.5 GAL.',
    price: 55.99,
    stock: 38,
    barcode: '787787160010',
    sku: 'W160',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w160-prime-2-bond-6235229.jpg',
    brand: 'WECO',
    rating: 4.8,
    reviewCount: 36,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p67',
    name: 'Weco W500 Level Tech Primer',
    slug: 'weco-w500-level-tech-primer',
    description: 'Primer specifically formulated for self-leveling compound applications. Seals porous substrates and improves adhesion of leveling compounds.',
    price: 28.99,
    stock: 52,
    barcode: '787787500010',
    sku: 'W500',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w500-level-tech-primer-3763065.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 33,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p68',
    name: 'Weco W015 Ultra Bond Primer',
    slug: 'weco-w015-ultra-bond-primer',
    description: 'Ultra bonding primer for concrete, masonry, and plaster surfaces. Penetrates deeply to create a strong mechanical key for subsequent layers.',
    price: 11.99,
    stock: 95,
    barcode: '787787015010',
    sku: 'W015',
    imageUrl: 'https://wecosolutions.com/cdn/shop/products/w-015-ultra-bond-2842180.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 57,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p69',
    name: 'Weco W013 Anchor FX Bonding Primer',
    slug: 'weco-w013-anchor-fx-primer',
    description: 'Anchor bonding primer that creates a mechanical bond on smooth or non-porous surfaces. Ideal for glazed tiles, metal, and difficult substrates.',
    price: 29.99,
    stock: 48,
    barcode: '787787013010',
    sku: 'W013',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w013-anchor-fx-6409829.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 42,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p70',
    name: 'Weco W800 Acrylic Latex Admixture',
    slug: 'weco-w800-acrylic-latex',
    description: 'Acrylic admixture that enhances strength, bonding, and flexibility in mortar compositions. Replaces water in mortar mixes for improved performance. 1 GAL and 5 GAL.',
    price: 19.99,
    stock: 85,
    barcode: '787787800010',
    sku: 'W800',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w800-acrylic-latex-3165.jpg',
    brand: 'WECO',
    rating: 4.6,
    reviewCount: 64,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p71',
    name: 'Weco W522 Muriatic Acid Cleaner',
    slug: 'weco-w522-muriatic-acid',
    description: 'Professional-strength muriatic acid for cleaning tile, concrete, and masonry surfaces. Removes cement haze, efflorescence, and mineral deposits.',
    price: 13.99,
    stock: 75,
    barcode: '787787522010',
    sku: 'W522',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w522-muriatic-acid-2654790.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 82,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p72',
    name: 'Weco W502 Tile & Stone Cleaner',
    slug: 'weco-w502-tile-stone-cleaner',
    description: 'Specialized cleaner for tile and natural stone surfaces. Removes dirt, grease, and construction residue without damaging sealers or finishes.',
    price: 18.99,
    stock: 68,
    barcode: '787787502010',
    sku: 'W502',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/w502-tile-stone-cleaner-6596596.jpg',
    brand: 'WECO',
    rating: 4.5,
    reviewCount: 55,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p73',
    name: 'Cortag Grout Float Trowel',
    slug: 'cortag-grout-trowel',
    description: 'Specialized rubber-faced trowel for applying and finishing grout in tile joints. Ergonomic handle for comfortable use. Professional-grade tool.',
    price: 13.29,
    stock: 60,
    barcode: '787787000730',
    sku: 'CT-GROUT-FL',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/cortag-grout-trowel-9615892.jpg',
    brand: 'Cortag',
    rating: 4.6,
    reviewCount: 48,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p74',
    name: 'Cortag Mixing Paddle Hexagonal 24"',
    slug: 'cortag-mixing-paddle-hexagonal-24',
    description: 'Heavy-duty hexagonal mixing paddle for adhesives, mortars, and compounds. Compatible with standard power drills. 24" length for deep bucket mixing.',
    price: 17.99,
    stock: 50,
    barcode: '787787000740',
    sku: 'CT-MIX-HEX-24',
    imageUrl: 'https://wecosolutions.com/cdn/shop/products/mixing-paddle-hexagonal-24-2740423.jpg',
    brand: 'Cortag',
    rating: 4.5,
    reviewCount: 39,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p75',
    name: 'Cortag Variable Speed Mixer HM-140',
    slug: 'cortag-variable-speed-mixer-hm-140',
    description: 'High-power electric variable speed mixer for consistent blending of adhesives, mortars, and tile compounds. Adjustable speed control for different material viscosities.',
    price: 189.99,
    comparePrice: 229.99,
    stock: 18,
    barcode: '787787000750',
    sku: 'CT-HM-140',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/variable-speed-mixer-hm-140-8152613.jpg',
    brand: 'Cortag',
    rating: 4.8,
    reviewCount: 27,
    featured: true,
    categoryId: 'c17',
  },
  {
    id: 'p76',
    name: 'Cortag Tile Spacer 1.0mm (1/32")',
    slug: 'cortag-tile-spacer-1mm',
    description: 'Durable plastic tile spacers for achieving precise grout lines in tile installations. 1.0mm (1/32") gap. Pack of 100.',
    price: 4.99,
    stock: 200,
    barcode: '787787000761',
    sku: 'CT-SP-1MM',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/cortag-spacer-10mm-132-4034108.jpg',
    brand: 'Cortag',
    rating: 4.5,
    reviewCount: 72,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p77',
    name: 'Cortag Tile Spacer 3.0mm (1/8")',
    slug: 'cortag-tile-spacer-3mm',
    description: 'Durable plastic tile spacers for achieving precise grout lines. 3.0mm (1/8") gap — the most common size for floor tile installation. Pack of 100.',
    price: 4.99,
    stock: 200,
    barcode: '787787000763',
    sku: 'CT-SP-3MM',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/cortag-spacer-30mm-18-9463156.jpg',
    brand: 'Cortag',
    rating: 4.6,
    reviewCount: 89,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p78',
    name: 'Cortag Diamond Cutting Blade Eco Segmented',
    slug: 'cortag-diamond-blade-eco-segmented',
    description: 'Economy segmented diamond blade for cutting ceramic, porcelain, and stone tile. Compatible with standard angle grinders.',
    price: 14.29,
    stock: 80,
    barcode: '787787000780',
    sku: 'CT-BLADE-ECO',
    imageUrl: 'https://wecosolutions.com/cdn/shop/products/diamond-cutting-blade-eco-segmented-7140856.jpg',
    brand: 'Cortag',
    rating: 4.4,
    reviewCount: 63,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p79',
    name: 'Cortag Diamond Cutting Blade Professional 7"',
    slug: 'cortag-diamond-blade-professional-7',
    description: 'Professional-grade 7" diamond blade for wet or dry cutting of ceramic, porcelain, and natural stone. Superior cutting speed and long blade life.',
    price: 54.99,
    stock: 35,
    barcode: '787787000797',
    sku: 'CT-BLADE-PRO-7',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/diamond-cutting-blade-professional-7-2433605.jpg',
    brand: 'Cortag',
    rating: 4.7,
    reviewCount: 44,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p80',
    name: 'Cortag Manual Tile Cutter Top 62 (24")',
    slug: 'cortag-manual-tile-cutter-top-62',
    description: 'Professional manual tile cutter with 24" cutting capacity. Precision scoring wheel and breaking mechanism for clean, straight cuts on ceramic and porcelain tiles.',
    price: 212.99,
    comparePrice: 249.99,
    stock: 12,
    barcode: '787787000800',
    sku: 'CT-CUT-TOP62',
    imageUrl: 'https://wecosolutions.com/cdn/shop/files/manual-tile-cutter-top-62-24-8671796.jpg',
    brand: 'Cortag',
    rating: 4.7,
    reviewCount: 31,
    featured: true,
    categoryId: 'c17',
  },
  {
    id: 'p37',
    name: 'Crossco® Silicone-Plus™ Roof Sealant',
    slug: 'crossco-silicone-plus-roof-sealant',
    description: 'A single-component, moisture-cured, fluid-applied silicone coating formulated for low VOC compliance. Provides excellent protection against water intrusion, UV exposure, and weathering across various building surfaces.',
    price: 59.99,
    comparePrice: 74.99,
    stock: 35,
    barcode: '787756300195',
    sku: 'RS033',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2020/07/super-white-finish-crossco-roof-sealants-rs400-2-64_1000.jpg',
    brand: 'CROSSCO',
    rating: 4.8,
    reviewCount: 47,
    featured: true,
    categoryId: 'c9',
  },

  // ── Bull-Bond® — Waterproofing & Construction Products ──
  {
    id: 'p81',
    name: 'Bull-Bond® Sabakrete™',
    slug: 'bullbond-sabakrete',
    description: 'Synthetic rubber latex admixture serving as a bonding adhesive and cement fortifier. Non re-emulsifiable and highly water resistant. Improves concrete repair properties and creates waterproof bonds on roofs, walls, and submerged structures.',
    price: 34.99,
    stock: 90,
    barcode: '787788081010',
    sku: 'BB-SABAKRETE',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Sabakrete_Bull-Bond_Paila.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 64,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p82',
    name: 'Bull-Bond® Duro Seal™',
    slug: 'bullbond-duro-seal',
    description: 'Black synthetic rubber membrane for intercoat sealing and waterproofing beneath tiles on floors, bathrooms, terraces, and kitchens. Controls non-structural cracks up to 1/8" wide as an anti-fracture tile protection system.',
    price: 49.99,
    stock: 65,
    barcode: '787788082010',
    sku: 'BB-DUROSEAL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Duro-Seal_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 48,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p83',
    name: 'Bull-Bond® Elasto Filler™',
    slug: 'bullbond-elasto-filler',
    description: 'White acrylic elastomeric waterproofing sealant and filler for filling and concealing cracks and imperfections. High-solids, high-build formula. Mold, fungus, and algae resistant. Low VOC and non-toxic.',
    price: 29.99,
    stock: 80,
    barcode: '787788083010',
    sku: 'BB-ELASTOFILL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Elasto-Filler_Bull-Bond_Paila-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 52,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p84',
    name: 'Bull-Bond® Elasto Acryl™',
    slug: 'bullbond-elasto-acryl',
    description: 'High-solids penetrating primer with 100% acrylic transparent formulation. Penetrates concrete, masonry, and wood to saturate pores and micro-cracks for deep waterproofing. Tacky finish provides strong substrate adhesion for subsequent coatings.',
    price: 39.99,
    stock: 70,
    barcode: '787788084010',
    sku: 'BB-ELASTOACRYL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Elasto-Acryl_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 43,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p85',
    name: 'Bull-Bond® Pro Sil® RED Primer FC',
    slug: 'bullbond-pro-sil-red-primer',
    description: 'Fluid-applied, water-based silicone adhesion promoting primer for PRO-SIL® TOP COAT silicone topcoats. Creates a high-tack finish for superior adhesion. Fast-drying, low VOC, and non-toxic.',
    price: 32.99,
    stock: 55,
    barcode: '787788085010',
    sku: 'BB-PROSILRED',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Sil-Red-Primer_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 37,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p86',
    name: 'Bull-Bond® Primer Plus™',
    slug: 'bullbond-primer-plus',
    description: '100% acrylic penetrating primer with semi-transparent red finish. Protective barrier against water and moisture on concrete, masonry, wood, and metal. Ultra-small particle size for deep penetration and permanent pore saturation.',
    price: 34.99,
    stock: 75,
    barcode: '787788086010',
    sku: 'BB-PRIMERPLUS',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Primer-Plus_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 58,
    featured: false,
    categoryId: 'c15',
  },
  {
    id: 'p87',
    name: 'Bull-Bond® Elasto Seal™ PRO',
    slug: 'bullbond-elasto-seal-pro',
    description: 'Poly-acrylic elastomeric cool roof coating. Ultra-white finish redirects solar heat, reducing cooling costs while protecting against water and UV damage. Permanent flexibility and high durability.',
    price: 54.99,
    comparePrice: 64.99,
    stock: 50,
    barcode: '787788087010',
    sku: 'BB-ELASTOSEAL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Elasto-Seal-_Bull-Bond_Paila_13-scaled.png',
    brand: 'Bull-Bond',
    rating: 4.8,
    reviewCount: 71,
    featured: true,
    categoryId: 'c13',
  },
  {
    id: 'p88',
    name: 'Bull-Bond® Top Seal™',
    slug: 'bullbond-top-seal',
    description: '100% acrylic polymer waterproofing coating. Functions as both primer and sealer (2-in-1). Ultra-white reflective finish reduces roof temperature. UV, mildew, fungi, and algae resistant. Applies light blue, cures white.',
    price: 49.99,
    stock: 55,
    barcode: '787788088010',
    sku: 'BB-TOPSEAL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Top-Seal-_Bull-Bond_Paila_32-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 62,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p89',
    name: 'Bull-Bond® Sil Mastic™',
    slug: 'bullbond-sil-mastic',
    description: 'High-performance silicone-based mastic sealant for waterproofing joints, seams, and penetrations on roofs and walls. Exceptional flexibility and weather resistance.',
    price: 44.99,
    stock: 48,
    barcode: '787788089010',
    sku: 'BB-SILMASTIC',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Sil-Mastic_Bull-Bond_Paila-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 34,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p90',
    name: 'Bull-Bond® Sil™ HS',
    slug: 'bullbond-sil-hs',
    description: 'High-solids, 100% silicone-based waterproofing cool roof coating. Single-component, moisture-cured. 100% hydrophobic and waterproof. Suitable for ponded water. Ultra-white finish for high heat reflectivity. Bacteria, fungi, and algae resistant.',
    price: 59.99,
    comparePrice: 74.99,
    stock: 40,
    barcode: '787788090010',
    sku: 'BB-SILHS',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Sil-HS_Bull-Bond_Paila-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.8,
    reviewCount: 45,
    featured: true,
    categoryId: 'c13',
  },
  {
    id: 'p91',
    name: 'Bull-Bond® Pro Sil® Top Coat',
    slug: 'bullbond-pro-sil-top-coat',
    description: 'High-solids, 100% silicone elastomeric coating for waterproofing tropical climate roofs. Reflects heat and UV rays. NSF P151 certified for rainwater catchment. Fully hydrophobic. Inert to bacteria, fungi, and algae.',
    price: 64.99,
    comparePrice: 79.99,
    stock: 38,
    barcode: '787788091010',
    sku: 'BB-PROSILTC',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Sil_Bull-Bond_Paila_24-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.9,
    reviewCount: 53,
    featured: true,
    categoryId: 'c13',
  },
  {
    id: 'p92',
    name: 'Bull-Bond® Proflex™',
    slug: 'bullbond-proflex',
    description: 'Fiber-reinforced styrene acrylic elastomeric cool roof coating. Fiber reinforcement provides durability, tension resistance, and crack-bridging. Applies blue, cures ultra-white. Mildew, fungus, and algae resistant. Low VOC.',
    price: 52.99,
    stock: 45,
    barcode: '787788092010',
    sku: 'BB-PROFLEX',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Flex_Bull-Bond_Paila_26-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 49,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p93',
    name: 'Bull-Bond® Pro One™',
    slug: 'bullbond-pro-one',
    description: '100% acrylic, elastomeric, silicone-modified cool roof coating. Seals, protects, and waterproofs roofs in tropical climates. Ultra-white finish reflects heat and UV. Complies with ASTM D-6083. Applies blue, cures ultra-white.',
    price: 49.99,
    stock: 52,
    barcode: '787788093010',
    sku: 'BB-PROONE',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-One_Bull-Bond_Paila_23-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 41,
    featured: false,
    categoryId: 'c13',
  },
  {
    id: 'p94',
    name: 'Bull-Bond® General Repair™',
    slug: 'bullbond-general-repair',
    description: 'Polymer-modified cement mortar for patching and leveling cement-based surfaces. Application range 1/8" to 1". For concrete roof leveling, drainage channels, parapet repair, irregular surface correction, and mortar bed applications.',
    price: 19.99,
    stock: 110,
    barcode: '787788094010',
    sku: 'BB-GENREPAIR',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/General-Repair_Bull-Bond_Paila-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 77,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p95',
    name: 'Bull-Bond® Micro-Topping™',
    slug: 'bullbond-micro-topping',
    description: 'Polymer-modified cementitious coating for concrete surface renewal. Mixed with latex admixtures for smooth finishing on roofs, walls, and floors. Suitable for water tanks, pools, basements, and BUR recovery systems. Creates ideal surface for elastomeric coatings.',
    price: 22.99,
    stock: 85,
    barcode: '787788095010',
    sku: 'BB-MICROTOPP',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Micro-Topping_Bull-Bond_Paila-1-scaled.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 55,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p96',
    name: 'Bull-Bond® Self Leveling™',
    slug: 'bullbond-self-leveling',
    description: 'Self-leveling cementitious mortar that seeks its own level and produces a smooth, flat, hard surface. Ideal for correcting uneven floors before tile installation or waterproofing applications.',
    price: 24.99,
    stock: 75,
    barcode: '787788096010',
    sku: 'BB-SELFLEVEL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Self-Leveling_Bull-Bond_Paila-1-scaled.png',
    brand: 'Bull-Bond',
    rating: 4.5,
    reviewCount: 48,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p97',
    name: 'Bull-Bond® Pro Level™',
    slug: 'bullbond-pro-level',
    description: 'Latex-modified self-leveling cement system for roof leveling and surface repairs. Prevents water ponding. Range: 1/8" to 3/4" without aggregate, up to 2" with aggregate extension. Fast curing, no shrinkage, superior substrate adhesion.',
    price: 26.99,
    stock: 70,
    barcode: '787788097010',
    sku: 'BB-PROLEVEL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Level-_Bull-Bond_Paila_12-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 39,
    featured: false,
    categoryId: 'c14',
  },
  {
    id: 'p98',
    name: 'Bull-Bond® PVC Corner Beads',
    slug: 'bullbond-pvc-corner-beads',
    description: 'PVC plastic corner beads for concrete and block walls. Rustproof, high-impact resistant construction. Flanged design with holes allows stucco to flow through for enhanced corner strength. For interior and exterior use.',
    price: 12.99,
    stock: 120,
    barcode: '787788098010',
    sku: 'BB-CORNERBD',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Corner-Beads_Bull-Bond-scaled.png',
    brand: 'Bull-Bond',
    rating: 4.5,
    reviewCount: 63,
    featured: false,
    categoryId: 'c17',
  },
  {
    id: 'p99',
    name: 'Bull-Bond® Contact Cement',
    slug: 'bullbond-contact-cement',
    description: 'Construction-grade contact adhesive with red polychloroprene base. Engineered for instant and permanent bonding of plastic corner beads and PVC stucco accessories to concrete, masonry, and plaster.',
    price: 34.99,
    stock: 60,
    barcode: '787788099010',
    sku: 'BB-CONTACTCEM',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2026/01/CONTAC-CEMENT_Corner-Bead-600x600.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 44,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p100',
    name: 'Bull-Bond® Concryl™',
    slug: 'bullbond-concryl',
    description: 'Acrylic co-polymer latex solution — non re-emulsifiable and water-resistant. Enhances Portland cement mixes and acts as a bonding primer. Improves compressive strength, tensile strength, and water resistance. Meets ASTM C-1059 Type II and ASTM C-932.',
    price: 29.99,
    stock: 80,
    barcode: '787788100010',
    sku: 'BB-CONCRYL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Concryl_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 57,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p101',
    name: 'Bull-Bond® Super PC™',
    slug: 'bullbond-super-pc',
    description: 'Cement-fortifying additive designed to enhance adhesive and concrete performance. Improves bonding, flexibility, and water resistance in cementitious mixes.',
    price: 24.99,
    stock: 72,
    barcode: '787788101010',
    sku: 'BB-SUPERPC',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Super-PC_Bull-Bond_Paila_29-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 38,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p102',
    name: 'Bull-Bond® Blue Bond™',
    slug: 'bullbond-blue-bond',
    description: 'Water-based latex polymer adhesive for plastering applications. Re-emulsifiable for permanent bond of fresh cement mortars to concrete. Eliminates mechanical fastening, increases plaster speed, and reduces waste. Meets ASTM C-932, C-631, MIL-B-19235.',
    price: 22.99,
    stock: 95,
    barcode: '787788102010',
    sku: 'BB-BLUEBOND',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Bull-Bond_Bull-Bond_Paila_2-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 82,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p103',
    name: 'Bull-Bond® Bonding Agent™',
    slug: 'bullbond-bonding-agent',
    description: 'Re-emulsifiable PVA/latex polymer bonding adhesive for plastering on existing concrete. Blue color for application visibility. For interior and exterior vertical concrete wall surfaces. Meets ASTM C-932, C-631, MIL-B-19235.',
    price: 19.99,
    stock: 100,
    barcode: '787788103010',
    sku: 'BB-BONDAGENT',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Bonding-Agent_Bull-Bond_Paila_4-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 91,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p104',
    name: 'Bull-Bond® TEX-GOLD™',
    slug: 'bullbond-tex-gold',
    description: 'Liquid synthetic polymer adhesive with texturized finish and Quick Grip mechanical adhesion. Yellow color for visibility. Bonds fresh cement mortars to concrete on walls and ceilings. Meets ASTM C-932, C-631, MIL-B-19235.',
    price: 24.99,
    stock: 88,
    barcode: '787788104010',
    sku: 'BB-TEXGOLD',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Tex-Gold_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 66,
    featured: false,
    categoryId: 'c12',
  },
  {
    id: 'p105',
    name: 'Bull-Bond® Anti-Crack™',
    slug: 'bullbond-anti-crack',
    description: 'Additive for fine sand plastering mortars. Improves workability, reduces shrinkage, and controls gradual setting in hot and windy conditions. Replaces lime. Increases compressive strength and water retention while reducing waste.',
    price: 18.99,
    stock: 105,
    barcode: '787788105010',
    sku: 'BB-ANTICRACK',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Anti-Crack_Bull-Bond.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 73,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p106',
    name: 'Bull-Bond® Cure & Seal™',
    slug: 'bullbond-cure-and-seal',
    description: 'Concrete curing and sealing compound that retains moisture in fresh concrete for proper curing while simultaneously sealing the surface. Reduces dust, improves hardness, and protects against moisture and chemical penetration.',
    price: 32.99,
    stock: 65,
    barcode: '787788106010',
    sku: 'BB-CURESEAL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Cure-Seal-_Bull-Bond_Paila_8-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 42,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p107',
    name: 'Bull-Bond® Enviro Mold™',
    slug: 'bullbond-enviro-mold',
    description: 'Concrete mold release agent available in paste and ready-to-use formulations. Provides clean, efficient release of concrete from forms and molds without staining or residue buildup.',
    price: 27.99,
    stock: 55,
    barcode: '787788107010',
    sku: 'BB-ENVIROMOLD',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Enviro-Mold_Bull-Bond_Paila_14-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.5,
    reviewCount: 31,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p108',
    name: 'Bull-Bond® Form Off™',
    slug: 'bullbond-form-off',
    description: 'Concrete form release agent designed for efficient mold release on concrete pours. Prevents concrete adhesion to forms for clean removal and reusability.',
    price: 22.99,
    stock: 60,
    barcode: '787788108010',
    sku: 'BB-FORMOFF',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Form-Off-VOC_Bull-Bond_Paila_15-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.5,
    reviewCount: 28,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p109',
    name: 'Bull-Bond® Kleancrete™',
    slug: 'bullbond-kleancrete',
    description: 'Professional concrete cleaning agent that removes efflorescence, rust stains, mineral deposits, and construction residue from concrete and masonry surfaces.',
    price: 19.99,
    stock: 70,
    barcode: '787788109010',
    sku: 'BB-KLEANCRETE',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Klearcreate_Bull-Bond_Paila_16-scaled.png',
    brand: 'Bull-Bond',
    rating: 4.5,
    reviewCount: 36,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p110',
    name: 'Bull-Bond® Clear Seal™ 2000',
    slug: 'bullbond-clear-seal-2000',
    description: 'Water-based 100% acrylic waterproofing sealer and primer for concrete, masonry, pavers, and plaster. Non-yellowing, stain-protective. Chemical resistant to gasoline, oil, chlorine, and salt. Binds paving joint sand.',
    price: 34.99,
    stock: 75,
    barcode: '787788110010',
    sku: 'BB-CLEARSEAL',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Clear-Seal_Bull-Bond_Paila_5-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 54,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p111',
    name: 'Bull-Bond® Duro Cure™',
    slug: 'bullbond-duro-cure',
    description: 'High-performance concrete curing compound that maintains optimal moisture for proper concrete hydration. Reduces shrinkage cracking and improves surface hardness and durability.',
    price: 28.99,
    stock: 58,
    barcode: '787788111010',
    sku: 'BB-DUROCURE',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Duro-Cure_Bull-Bond_Paila_9-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 33,
    featured: false,
    categoryId: 'c16',
  },
  {
    id: 'p112',
    name: 'Bull-Bond® Traffic Paint™',
    slug: 'bullbond-traffic-paint',
    description: 'Water-based enamel for pavement marking. Combines durability of oil-based paints with the ease and safety of water-based coatings. Rapid drying, strong adhesion to concrete and asphalt.',
    price: 29.99,
    stock: 65,
    barcode: '787788112010',
    sku: 'BB-TRAFFICPNT',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Trafic-Paint_Bull-Bond_Paila_33-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 47,
    featured: false,
    categoryId: 'c18',
  },
  {
    id: 'p113',
    name: 'Bull-Bond® Pro Floor™',
    slug: 'bullbond-pro-floor',
    description: 'Durable floor paint for concrete and masonry floors. Provides a hard-wearing, easy-to-clean surface resistant to foot traffic, chemicals, and abrasion.',
    price: 34.99,
    stock: 55,
    barcode: '787788113010',
    sku: 'BB-PROFLOOR',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Floor_Bull-Bond_Paila_21-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 39,
    featured: false,
    categoryId: 'c18',
  },
  {
    id: 'p114',
    name: 'Bull-Bond® Pro Grip™',
    slug: 'bullbond-pro-grip',
    description: 'Water-based traffic paint with anti-slip properties for pavement markings. Quick-drying and high resistance. Strong adhesion to concrete and asphalt. Manufactured in Puerto Rico.',
    price: 32.99,
    stock: 60,
    barcode: '787788114010',
    sku: 'BB-PROGRIP',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Grip_Bull-Bond_Paila_22-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.6,
    reviewCount: 35,
    featured: false,
    categoryId: 'c18',
  },
  {
    id: 'p115',
    name: 'Bull-Bond® Sure Prime™',
    slug: 'bullbond-sure-prime',
    description: 'Stain-blocking primer for interior and exterior wall surfaces. Seals stains, equalizes surface porosity, and improves topcoat adhesion and coverage.',
    price: 27.99,
    stock: 70,
    barcode: '787788115010',
    sku: 'BB-SUREPRIME',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Sure-Prime_Bull-Bond_Paila_30-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.5,
    reviewCount: 44,
    featured: false,
    categoryId: 'c18',
  },
  {
    id: 'p116',
    name: 'Bull-Bond® Pro Wall Paint™',
    slug: 'bullbond-pro-wall-paint',
    description: '100% acrylic waterproofing primer with ultra-small particle size technology. Blocks water intrusion, hides stains, resists mildew/fungus/algae, and improves paint adhesion on concrete, CMU, plaster, stucco, and gypsum surfaces.',
    price: 29.99,
    stock: 80,
    barcode: '787788116010',
    sku: 'BB-PROWALLPNT',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Wall-Primer_Bull-Bond_Paila_25-600x750.png',
    brand: 'Bull-Bond',
    rating: 4.7,
    reviewCount: 61,
    featured: false,
    categoryId: 'c18',
  },
  {
    id: 'p117',
    name: 'Bull-Bond® Pro Dry™',
    slug: 'bullbond-pro-dry',
    description: 'Acrylic waterproofing paint for concrete and masonry walls in tropical climates. Resists 15 psi negative hydrostatic pressure and 98 mph wind-driven rain. Mold, mildew, algae, and efflorescence resistant. Low VOC and non-toxic.',
    price: 34.99,
    comparePrice: 42.99,
    stock: 65,
    barcode: '787788117010',
    sku: 'BB-PRODRY',
    imageUrl: 'https://bullbond.com/wp-content/uploads/2025/11/Pro-Dry_Bull-Bond_Paila_20-scaled.png',
    brand: 'Bull-Bond',
    rating: 4.8,
    reviewCount: 58,
    featured: true,
    categoryId: 'c18',
  },
  // ── TOTAL Brand Hand Tools (scraped from totalbusiness.com) ──────────────
  {
    id: 'p118',
    name: 'Electric Soldering Iron 40W',
    slug: 'total-soldering-iron-40w',
    description: 'Electric soldering iron 40W, 220-240V~50/60Hz. Ideal for light electronic work, hobby projects, and wire connections.',
    price: 12.99,
    stock: 80,
    barcode: '787000011806',
    sku: 'TET1406',
    imageUrl: 'https://5.imimg.com/data5/ECOM/Default/2023/6/313479181/AC/VL/XI/161755969/1665738695999-tet1406-500x500.jpeg',
    brand: 'TOTAL',
    rating: 4.2,
    reviewCount: 34,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p119',
    name: 'Electric Soldering Iron 60W',
    slug: 'total-soldering-iron-60w',
    description: 'Electric soldering iron 60W, 220-240V~50/60Hz. Suitable for heavier electronic soldering tasks and plumbing connections.',
    price: 14.99,
    stock: 65,
    barcode: '787000011900',
    sku: 'TET1606',
    imageUrl: 'https://ik.imagekit.io/fepy/cdn/catalog/product/3/9/39345-pcs_3.jpg?format=webp',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 28,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p120',
    name: 'Electric Soldering Iron 60W Pro',
    slug: 'total-soldering-iron-60w-pro',
    description: 'Professional-grade 60W soldering iron, 220-240V~50/60Hz. Enhanced tip retention for extended professional use.',
    price: 15.99,
    stock: 50,
    barcode: '787000012000',
    sku: 'TET2606',
    imageUrl: 'https://ik.imagekit.io/fepy/cdn/catalog/product/3/9/39345-pcs_3.jpg?format=webp',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 21,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p121',
    name: 'Electric Soldering Iron 100W',
    slug: 'total-soldering-iron-100w',
    description: 'Heavy-duty 100W electric soldering iron, 220-240V~50/60Hz. For thick wires, large components, and demanding industrial tasks.',
    price: 18.99,
    stock: 40,
    barcode: '787000012100',
    sku: 'TET10006',
    imageUrl: 'https://totalperumsa.com/wp-content/uploads/2024/06/22690.jpg',
    brand: 'TOTAL',
    rating: 4.5,
    reviewCount: 17,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p122',
    name: '120-Piece Accessories Set',
    slug: 'total-120pc-accessories-set',
    description: '120-piece BMC-packaged accessories set. Includes drill bits, screwdriver bits, sockets, and more. Compatible with most power and hand tools.',
    price: 24.99,
    comparePrice: 32.99,
    stock: 55,
    barcode: '787000012200',
    sku: 'THKTAC01120',
    imageUrl: 'https://www.totalbusiness.com/userfiles/1/images/photo/20200730/THKTAC01120.JPG',
    brand: 'TOTAL',
    rating: 4.6,
    reviewCount: 89,
    featured: true,
    categoryId: 'c20',
  },
  {
    id: 'p123',
    name: 'Wire Brush 250mm',
    slug: 'total-wire-brush-250mm',
    description: 'Wire brush 250mm length with 0.3mm wire diameter. Removes rust, scale, and corrosion from metal surfaces effectively.',
    price: 7.99,
    stock: 120,
    barcode: '787000012300',
    sku: 'THT92102',
    imageUrl: 'https://www.totalbusiness.com/userfiles/1/images/photo/20200730/THT92102.PNG',
    brand: 'TOTAL',
    rating: 4.1,
    reviewCount: 45,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p124',
    name: 'Claw Hammer 8oz Fiberglass',
    slug: 'total-claw-hammer-8oz-fiberglass',
    description: 'Claw hammer 8oz/220g with durable fiberglass handle. Balanced for light framing, nailing, and household repairs.',
    price: 12.99,
    stock: 95,
    barcode: '787000012400',
    sku: 'THT7386',
    imageUrl: 'https://www.totalbusiness.com/website-center/upload/images/1428b6bf524644e88113c40306cb9ee7.jpg',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 62,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p125',
    name: 'Claw Hammer 16oz Fiberglass',
    slug: 'total-claw-hammer-16oz-fiberglass',
    description: 'Claw hammer 16oz/450g with fiberglass handle. Standard framing weight — versatile for construction, renovation, and carpentry.',
    price: 15.99,
    stock: 110,
    barcode: '787000012500',
    sku: 'THT73166',
    imageUrl: 'https://www.totalbusiness.com/website-center/upload/images/1428b6bf524644e88113c40306cb9ee7.jpg',
    brand: 'TOTAL',
    rating: 4.5,
    reviewCount: 98,
    featured: true,
    categoryId: 'c20',
  },
  {
    id: 'p126',
    name: 'Claw Hammer 8oz Hardwood',
    slug: 'total-claw-hammer-8oz-hardwood',
    description: 'Claw hammer 8oz/220g with classic hardwood handle. Comfortable grip for light-duty nailing and household use.',
    price: 11.99,
    stock: 75,
    barcode: '787000012600',
    sku: 'THTW7308',
    imageUrl: 'https://www.totalbusiness.com/userfiles/1/images/photo/200818143265322/THTW7308.JPG',
    brand: 'TOTAL',
    rating: 4.2,
    reviewCount: 41,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p127',
    name: 'Claw Hammer 16oz Hardwood',
    slug: 'total-claw-hammer-16oz-hardwood',
    description: 'Claw hammer 16oz/450g with hardwood handle. Traditional design for reliable everyday nailing and demolition tasks.',
    price: 13.99,
    stock: 85,
    barcode: '787000012700',
    sku: 'THTW7316',
    imageUrl: 'https://www.totalbusiness.com/userfiles/1/images/photo/20200730/THTW7316.jpg',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 53,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p134',
    name: 'Ball Pein Hammer 16oz Fiberglass',
    slug: 'total-ball-pein-hammer-16oz-fiberglass',
    description: 'Ball pein hammer 16oz/450g with fiberglass handle. Essential for metalworking, rounding edges, and driving cold chisels.',
    price: 16.99,
    stock: 70,
    barcode: '787000013400',
    sku: 'THT74166',
    imageUrl: 'https://www.totalbusiness.com/website-center/upload/images/2440a83a5a7143b28916cf56c2c9cfca.jpg',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 47,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p135',
    name: 'Ball Pein Hammer 24oz Fiberglass',
    slug: 'total-ball-pein-hammer-24oz-fiberglass',
    description: 'Ball pein hammer 24oz/660g with fiberglass handle. Extra weight for heavier metalwork, engine repair, and rivet setting.',
    price: 19.99,
    stock: 55,
    barcode: '787000013500',
    sku: 'THT74246',
    imageUrl: 'https://www.totalbusiness.com/website-center/upload/images/34034c64114841c88763d960eadcff6d.jpg',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 31,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p136',
    name: 'Ball Pein Hammer 16oz Hardwood',
    slug: 'total-ball-pein-hammer-16oz-hardwood',
    description: 'Ball pein hammer 16oz/450g with hardwood handle. Classic design for metalwork, automotive repair, and workshop projects.',
    price: 14.99,
    stock: 60,
    barcode: '787000013600',
    sku: 'THTW7416',
    imageUrl: 'https://www.totalbusiness.com/userfiles/1/images/photo/200818143265322/THTW7416.JPG',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 26,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p137',
    name: 'Ball Pein Hammer 24oz Hardwood',
    slug: 'total-ball-pein-hammer-24oz-hardwood',
    description: 'Ball pein hammer 24oz/660g with hardwood handle. Sturdy and balanced for heavy metalworking and industrial applications.',
    price: 17.99,
    stock: 45,
    barcode: '787000013700',
    sku: 'THTW7424',
    imageUrl: 'https://www.totalbusiness.com/userfiles/1/images/photo/200818143265322/THTW7424.JPG',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 19,
    featured: false,
    categoryId: 'c20',
  },

  {
    id: 'p143',
    name: 'Sledge Hammer 10LB',
    slug: 'total-sledge-hammer-10lb',
    description: 'Sledge hammer 10LB with fiberglass handle. For demolition, driving stakes, breaking concrete, and heavy construction work.',
    price: 29.99,
    comparePrice: 37.99,
    stock: 30,
    barcode: '787000014300',
    sku: 'THT750416',
    imageUrl: 'https://ik.imagekit.io/fepy/cdn/catalog/product/t/h/tht750416_1.png?format=webp&tr=w-800,h-800,fo-auto',
    brand: 'TOTAL',
    rating: 4.6,
    reviewCount: 54,
    featured: true,
    categoryId: 'c20',
  },
  {
    id: 'p144',
    name: 'Sledge Hammer 12LB',
    slug: 'total-sledge-hammer-12lb',
    description: 'Sledge hammer 12LB with fiberglass handle. Maximum impact for heavy demolition, driving railroad spikes, and breaking rock.',
    price: 34.99,
    comparePrice: 44.99,
    stock: 22,
    barcode: '787000014400',
    sku: 'THT750516',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600',
    brand: 'TOTAL',
    rating: 4.7,
    reviewCount: 41,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p147',
    name: 'Rubber Hammer 8oz',
    slug: 'total-rubber-hammer-8oz',
    description: 'Rubber hammer 8oz/220g with fiberglass handle. Non-marking strikes for tile setting, woodworking, and assembly work.',
    price: 11.99,
    stock: 90,
    barcode: '787000014700',
    sku: 'THT76816',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 56,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p148',
    name: 'Rubber Hammer 16oz',
    slug: 'total-rubber-hammer-16oz',
    description: 'Rubber hammer 16oz/450g with fiberglass handle. Heavier mallet for flooring installation, tile setting, and cabinet assembly.',
    price: 13.99,
    stock: 75,
    barcode: '787000014800',
    sku: 'THT761616',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 48,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p149',
    name: 'Rubber & Plastic Hammer 40mm',
    slug: 'total-rubber-plastic-hammer-40mm',
    description: 'Dual-face rubber and plastic hammer 40mm. Soft-face mallet for delicate assembly, furniture, and surface-sensitive work.',
    price: 14.99,
    stock: 60,
    barcode: '787000014900',
    sku: 'THT77406',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 37,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p150',
    name: 'Combination Pliers 6"',
    slug: 'total-combination-pliers-6in',
    description: 'Combination pliers 6"/160mm. Multi-purpose grip, cut, and bend tool for electrical work, wire handling, and general use.',
    price: 9.99,
    stock: 130,
    barcode: '787000015000',
    sku: 'THT110606P',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 72,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p151',
    name: 'Combination Pliers 7"',
    slug: 'total-combination-pliers-7in',
    description: 'Combination pliers 7"/180mm. Longer reach for gripping, bending, and cutting in tighter spaces and electrical panels.',
    price: 11.99,
    stock: 110,
    barcode: '787000015100',
    sku: 'THT110706P',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 65,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p152',
    name: 'Combination Pliers 8"',
    slug: 'total-combination-pliers-8in',
    description: 'Combination pliers 8"/200mm. Maximum leverage for heavy-duty gripping, twisting, and cutting applications.',
    price: 13.99,
    stock: 85,
    barcode: '787000015200',
    sku: 'THT110806P',
    imageUrl: 'https://ik.imagekit.io/fepy/cdn/catalog/product/t/h/tht110806p_1.png?format=webp&tr=w-800,h-800,fo-auto',
    brand: 'TOTAL',
    rating: 4.5,
    reviewCount: 58,
    featured: true,
    categoryId: 'c20',
  },
  {
    id: 'p153',
    name: 'Diagonal Cutting Pliers 6"',
    slug: 'total-diagonal-cutting-pliers-6in',
    description: 'Diagonal cutting pliers 6"/160mm. Precision cutting of wire, cable ties, and leads in electronics and electrical work.',
    price: 9.99,
    stock: 100,
    barcode: '787000015300',
    sku: 'THT130606P',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 49,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p154',
    name: 'Diagonal Cutting Pliers 7"',
    slug: 'total-diagonal-cutting-pliers-7in',
    description: 'Diagonal cutting pliers 7"/180mm. Clean cuts on thicker wire and cable with improved leverage.',
    price: 11.99,
    stock: 90,
    barcode: '787000015400',
    sku: 'THT130706P',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 43,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p155',
    name: 'Heavy-Duty Diagonal Cutting Pliers 7"',
    slug: 'total-hd-diagonal-cutting-pliers-7in',
    description: 'Heavy-duty diagonal cutting pliers 7"/180mm. Reinforced jaws for cutting hardened wire, bolts, and thick cable.',
    price: 14.99,
    comparePrice: 18.99,
    stock: 70,
    barcode: '787000015500',
    sku: 'THT1776P',
    imageUrl: 'https://www.totalbusiness.com/website-center/upload/images/f338364f0852485395f88b6cc502983b.jpg',
    brand: 'TOTAL',
    rating: 4.6,
    reviewCount: 61,
    featured: true,
    categoryId: 'c20',
  },
  {
    id: 'p156',
    name: 'Long Nose Pliers 6"',
    slug: 'total-long-nose-pliers-6in',
    description: 'Long nose pliers 6"/160mm. Precise gripping and bending in confined spaces, ideal for electronics and jewelry work.',
    price: 10.99,
    stock: 95,
    barcode: '787000015600',
    sku: 'THT120606P',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'TOTAL',
    rating: 4.4,
    reviewCount: 67,
    featured: false,
    categoryId: 'c20',
  },
  {
    id: 'p157',
    name: 'Bent Nose Pliers 6"',
    slug: 'total-bent-nose-pliers-6in',
    description: 'Bent nose pliers 6"/160mm. Angled jaw for reaching around obstacles and gripping in awkward angles.',
    price: 10.99,
    stock: 80,
    barcode: '787000015700',
    sku: 'THT1466P',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'TOTAL',
    rating: 4.3,
    reviewCount: 44,
    featured: false,
    categoryId: 'c20',
  },
];
