// Seed script - JavaScript file demonstrating JS/TS mix per requirements
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

const categories = [
  { name: 'Tools', slug: 'tools', icon: '🔧' },
  { name: 'Building Materials', slug: 'building-materials', icon: '🧱' },
  { name: 'Plumbing', slug: 'plumbing', icon: '🚿' },
  { name: 'Electrical', slug: 'electrical', icon: '⚡' },
  { name: 'Paint', slug: 'paint', icon: '🎨' },
  { name: 'Garden', slug: 'garden', icon: '🌱' },
  { name: 'Hardware', slug: 'hardware', icon: '🔩' },
  { name: 'Lighting', slug: 'lighting', icon: '💡' },
  { name: 'Roof Sealing', slug: 'roof-sealing', icon: '🏠' },
];

const products = [
  {
    name: 'DEWALT 20V MAX Cordless Drill Kit',
    slug: 'dewalt-20v-cordless-drill',
    description: 'Compact, lightweight design fits into tight areas. High performance motor delivers 300 unit watts out (UWO) of power.',
    price: 199.99,
    comparePrice: 249.99,
    stock: 45,
    barcode: '885911599832',
    sku: 'DW-DCD771C2',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600',
    brand: 'DEWALT',
    rating: 4.8,
    reviewCount: 1247,
    featured: true,
    categorySlug: 'tools',
  },
  {
    name: 'Quikrete 60 lb. Concrete Mix',
    slug: 'quikrete-concrete-mix',
    description: 'Original 4000 PSI average compressive strength concrete mix. Use for any general concrete application.',
    price: 6.48,
    stock: 320,
    barcode: '039645011010',
    sku: 'QK-1101-60',
    imageUrl: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=600',
    brand: 'Quikrete',
    rating: 4.6,
    reviewCount: 892,
    featured: true,
    categorySlug: 'building-materials',
  },
  {
    name: 'Moen Single-Handle Kitchen Faucet',
    slug: 'moen-kitchen-faucet',
    description: 'Chrome finish with pull-down sprayer. Lifetime limited warranty. Easy installation.',
    price: 159.00,
    comparePrice: 199.00,
    stock: 28,
    barcode: '026508295731',
    sku: 'MN-87039',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600',
    brand: 'Moen',
    rating: 4.7,
    reviewCount: 543,
    featured: true,
    categorySlug: 'plumbing',
  },
  {
    name: 'Romex 12/2 Indoor Electrical Wire 250ft',
    slug: 'romex-12-2-wire',
    description: 'NM-B 12/2 with ground. UL listed. For indoor residential use.',
    price: 189.00,
    stock: 67,
    barcode: '038902031495',
    sku: 'RX-12-2-250',
    imageUrl: 'https://images.unsplash.com/photo-1565608087341-404b25492fee?w=600',
    brand: 'Southwire',
    rating: 4.9,
    reviewCount: 234,
    categorySlug: 'electrical',
  },
  {
    name: 'BEHR Premium Plus Interior Paint 1 Gal',
    slug: 'behr-interior-paint',
    description: 'Low VOC, eggshell finish. Excellent coverage and durability. Available in thousands of colors.',
    price: 32.98,
    stock: 156,
    barcode: '082474200056',
    sku: 'BH-PP-INT-1G',
    imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600',
    brand: 'BEHR',
    rating: 4.7,
    reviewCount: 2103,
    featured: true,
    categorySlug: 'paint',
  },
  {
    name: 'Miracle-Gro Garden Soil 1 cu ft',
    slug: 'miracle-gro-soil',
    description: 'Enriched with continuous release plant food. Feeds for up to 3 months. For in-ground use.',
    price: 8.97,
    stock: 412,
    barcode: '073561720205',
    sku: 'MG-GS-1CF',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600',
    brand: 'Miracle-Gro',
    rating: 4.5,
    reviewCount: 1567,
    categorySlug: 'garden',
  },
  {
    name: 'Stanley 25ft Tape Measure',
    slug: 'stanley-tape-measure',
    description: 'Heavy-duty tape with Mylar coating for extended blade life. Lifetime warranty.',
    price: 14.97,
    stock: 89,
    barcode: '076174330259',
    sku: 'ST-33-425',
    imageUrl: 'https://images.unsplash.com/photo-1426927308491-6380b6a9936f?w=600',
    brand: 'Stanley',
    rating: 4.8,
    reviewCount: 3421,
    categorySlug: 'tools',
  },
  {
    name: 'LED 60W Equivalent Daylight Bulb 4-Pack',
    slug: 'led-60w-bulb-4pack',
    description: 'Energy-saving LED bulb. 800 lumens. 5000K daylight. Lasts up to 15,000 hours.',
    price: 9.97,
    stock: 234,
    barcode: '046135710179',
    sku: 'LED-60W-4PK',
    imageUrl: 'https://images.unsplash.com/photo-1550985543-49bee3167284?w=600',
    brand: 'EcoSmart',
    rating: 4.6,
    reviewCount: 4521,
    featured: true,
    categorySlug: 'lighting',
  },
  {
    name: 'Everbilt 5lb Box of Drywall Screws',
    slug: 'everbilt-drywall-screws',
    description: 'Coarse thread, bugle head. Phosphate coated. For wood studs.',
    price: 18.47,
    stock: 145,
    barcode: '030699137497',
    sku: 'EB-DS-5LB',
    imageUrl: 'https://images.unsplash.com/photo-1609205807490-89c0d6c8c5ea?w=600',
    brand: 'Everbilt',
    rating: 4.7,
    reviewCount: 678,
    categorySlug: 'hardware',
  },
  {
    name: 'RYOBI 18V Circular Saw',
    slug: 'ryobi-circular-saw',
    description: '5-1/2 in. blade. Lightweight design. Tool only - battery sold separately.',
    price: 79.00,
    stock: 32,
    barcode: '033287204472',
    sku: 'RY-P505',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600',
    brand: 'RYOBI',
    rating: 4.6,
    reviewCount: 891,
    categorySlug: 'tools',
  },
  {
    name: 'PEX Tubing 1/2 in. x 100 ft',
    slug: 'pex-tubing-half-inch',
    description: 'Red PEX-B for hot water lines. NSF certified. Flexible and durable.',
    price: 38.50,
    stock: 78,
    barcode: '079916020013',
    sku: 'PEX-12-100R',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=600',
    brand: 'SharkBite',
    rating: 4.8,
    reviewCount: 312,
    categorySlug: 'plumbing',
  },
  {
    name: 'Heavy Duty Wheelbarrow 6 cu ft',
    slug: 'wheelbarrow-6cuft',
    description: 'Steel tray, hardwood handles. Pneumatic tire. Great for gardening and construction.',
    price: 89.00,
    comparePrice: 119.00,
    stock: 24,
    barcode: '745035811563',
    sku: 'WB-6CF-HD',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600',
    brand: 'True Temper',
    rating: 4.5,
    reviewCount: 234,
    categorySlug: 'garden',
  },
  {
    name: 'Crossco® Water Guard™ 5 Gal',
    slug: 'crossco-water-guard',
    description: 'High-performance 3-in-1 sealant, primer, and paint with strong resistance to alkalinity. Hydrophobic Bio-Pruf Technology waterproofs roofs and walls against water, moisture, and leaks. Stain resistant, energy-saving, and easy to clean. Available in matte or satin finish.',
    price: 59.99,
    comparePrice: 74.99,
    stock: 40,
    barcode: '787756100221',
    sku: 'CC-WG-5G',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2014/10/WG_satin.jpg',
    brand: 'CROSSCO',
    rating: 4.7,
    reviewCount: 198,
    featured: true,
    categorySlug: 'roof-sealing',
  },
  {
    name: 'Crossco® Tropical Flat™ 1 Gal',
    slug: 'crossco-tropical-flat',
    description: 'Matte latex paint formulated with acrylic resin for a smooth and uniform finish. Ideal for interior or exterior use on cement, wood, brick, and metal surfaces. Resistant to fungal growth, quick drying (touch-dry in 1 hour, recoat in 5 hours), and long-lasting durability.',
    price: 28.99,
    stock: 85,
    barcode: '787756100238',
    sku: 'CC-TF-1G',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2015/11/tropical_flat1.png',
    brand: 'CROSSCO',
    rating: 4.5,
    reviewCount: 134,
    categorySlug: 'paint',
  },
  {
    name: 'Crossco® Tropical Gloss™ 1 Gal',
    slug: 'crossco-tropical-gloss',
    description: 'Semi-gloss latex paint suitable for interior or exterior surfaces. Designed for industrial, commercial, and residential use on cement, wood, brick, and metal. Fungus resistant, does not yellow over time, easy to clean, and touch-dry in 1 hour.',
    price: 32.99,
    stock: 72,
    barcode: '787756100245',
    sku: 'CC-TG-1G',
    imageUrl: 'https://www.crosscopr.com/wp-content/uploads/2015/11/tropical_gloss-2.png',
    brand: 'CROSSCO',
    rating: 4.6,
    reviewCount: 109,
    categorySlug: 'paint',
  },
  {
    name: 'Piedra 3/4"',
    slug: 'piedra-3-4',
    description: 'Piedra triturada gris de 3/4 de pulgada. Ideal para mezclas de concreto, rellenos de drenaje y paisajismo. Material local de alta resistencia.',
    price: 9.99,
    stock: 500,
    barcode: '787756200016',
    sku: 'NC-PIEDRA-34',
    imageUrl: 'https://scontent.fhsv1-1.fna.fbcdn.net/v/t39.30808-6/473556405_1096243035853987_565815375_n.jpg',
    brand: 'Naguabo Commercial',
    rating: 4.8,
    reviewCount: 62,
    featured: false,
    categorySlug: 'building-materials',
  },
  {
    name: 'Piedra Blanca 3/4"',
    slug: 'piedra-blanca-3-4',
    description: 'Piedra caliza blanca triturada de 3/4 de pulgada. Popular para proyectos de paisajismo, caminos y decoración exterior. Aspecto limpio y elegante.',
    price: 14.99,
    stock: 320,
    barcode: '787756200023',
    sku: 'NC-PIEDRA-BL-34',
    imageUrl: 'https://scontent.fhsv1-1.fna.fbcdn.net/v/t39.30808-6/473556405_1096243035853987_560579298_n.jpg',
    brand: 'Naguabo Commercial',
    rating: 4.7,
    reviewCount: 45,
    featured: false,
    categorySlug: 'building-materials',
  },
  {
    name: 'Piedra Dalmata',
    slug: 'piedra-dalmata',
    description: 'Piedra decorativa dálmata con patrón gris y blanco moteado. Perfecta para jardines, entradas y proyectos de decoración exterior que requieren un toque distintivo.',
    price: 18.99,
    stock: 210,
    barcode: '787756200030',
    sku: 'NC-PIEDRA-DAL',
    imageUrl: 'https://scontent.fhsv1-1.fna.fbcdn.net/v/t39.30808-6/473556405_1096243035853987_561149727_n.jpg',
    brand: 'Naguabo Commercial',
    rating: 4.9,
    reviewCount: 38,
    featured: false,
    categorySlug: 'building-materials',
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Create admin user
  const adminPassword = await bcrypt.hash('admin123', 10);
  await prisma.user.upsert({
    where: { email: 'admin@naguabo-commercial.com' },
    update: {},
    create: {
      email: 'admin@naguabo-commercial.com',
      name: 'Owner Admin',
      password: adminPassword,
      role: 'ADMIN',
    },
  });

  // Categories
  const catMap = {};
  for (const cat of categories) {
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    });
    catMap[cat.slug] = created.id;
  }

  // Products
  for (const p of products) {
    const { categorySlug, ...rest } = p;
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {},
      create: { ...rest, categoryId: catMap[categorySlug] },
    });
  }

  console.log('✅ Done seeding.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
